[project]
name = "reproducer-pg_doorman-missclick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "ansible>=11.6.0",
    "ansible-dev-tools>=25.5.2",
    "podman>=5.4.0.1",
]
