all:
  hosts:
    target_host:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_user: root
      ansible_ssh_private_key_file: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_python_interpreter: /usr/bin/python3